/**
 * Server-side RBAC and Segregation of Duties (SoD) Engine
 */
import { PermissionKey, RoleId, User } from '../types/index.ts';

export const ROLE_PERMISSIONS: Record<RoleId, PermissionKey[]> = {
  ANALYST: [
    'case:view',
    'case:edit',
    'case:submit_review',
    'subject:create_edit',
    'alias:propose',
    'screening:run',
    'screening:pause_resume',
    'manifest:view',
    'historical_exception:request',
    'saved_view:manage',
    'exemption:request',
    'policy:view',
    'audit:view',
    'event:view',
    'event:edit',
    'event:merge_split',
    'timeline:edit',
  ],
  CHECKER: [
    'case:view',
    'case:edit',
    'case:assign',
    'case:approve_close',
    'subject:create_edit',
    'alias:propose',
    'alias:approve',
    'screening:run',
    'screening:pause_resume',
    'manifest:view',
    'manifest:revise',
    'historical_exception:approve',
    'saved_view:manage',
    'exemption:approve',
    'policy:view',
    'audit:view',
    'event:view',
    'event:edit',
    'event:merge_split',
    'event:recluster',
    'timeline:edit',
  ],
  COMPLIANCE_OFFICER: [
    'case:view',
    'case:edit',
    'case:assign',
    'case:approve_close',
    'subject:create_edit',
    'alias:propose',
    'alias:approve',
    'screening:run',
    'screening:pause_resume',
    'manifest:view',
    'manifest:revise',
    'historical_exception:approve',
    'saved_view:manage',
    'exemption:approve',
    'policy:view',
    'search_config:edit',
    'audit:view',
    'audit:export',
    'event:view',
    'event:edit',
    'event:merge_split',
    'event:recluster',
    'timeline:edit',
  ],
  MLRO: [
    'case:view',
    'case:edit',
    'case:assign',
    'case:approve_close',
    'alias:approve',
    'screening:run',
    'screening:pause_resume',
    'manifest:view',
    'manifest:revise',
    'historical_exception:approve',
    'saved_view:manage',
    'exemption:approve',
    'policy:view',
    'search_config:edit',
    'audit:view',
    'audit:export',
    'event:view',
    'event:edit',
    'event:merge_split',
    'event:recluster',
    'timeline:edit',
  ],
  OPERATIONS_MANAGER: [
    'case:view',
    'case:assign',
    'manifest:view',
    'saved_view:manage',
    'policy:view',
    'audit:view',
    'audit:export',
    'event:view',
  ],
  POLICY_ADMINISTRATOR: [
    'manifest:view',
    'policy:view',
    'policy:edit',
    'search_config:edit',
    'audit:view',
    'event:view',
  ],
  SYSTEM_ADMINISTRATOR: [
    'connector:manage',
    'manifest:view',
    'policy:view',
    'audit:view',
    'event:view',
    'event:recluster',
  ],
  AUDITOR: [
    'case:view',
    'manifest:view',
    'saved_view:manage',
    'policy:view',
    'audit:view',
    'audit:export',
    'event:view',
  ],
};

export const DEMO_USERS: Record<RoleId, User> = {
  ANALYST: {
    id: 'usr-analyst-01',
    name: 'Sarah Chen',
    email: 'sarah.chen@compliance.bank',
    role: 'ANALYST',
    department: 'Financial Crime Investigations',
  },
  CHECKER: {
    id: 'usr-checker-02',
    name: 'Marcus Vance',
    email: 'marcus.vance@compliance.bank',
    role: 'CHECKER',
    department: 'Quality Assurance & 4-Eyes Review',
  },
  COMPLIANCE_OFFICER: {
    id: 'usr-comp-03',
    name: 'Elena Rostova',
    email: 'elena.rostova@compliance.bank',
    role: 'COMPLIANCE_OFFICER',
    department: 'Regulatory Compliance & Advisory',
  },
  MLRO: {
    id: 'usr-mlro-04',
    name: 'David Sterling, KC',
    email: 'david.sterling@compliance.bank',
    role: 'MLRO',
    department: 'Statutory AML Oversight',
  },
  OPERATIONS_MANAGER: {
    id: 'usr-ops-05',
    name: 'Priya Sharma',
    email: 'priya.sharma@compliance.bank',
    role: 'OPERATIONS_MANAGER',
    department: 'Screening Operations & SLA',
  },
  POLICY_ADMINISTRATOR: {
    id: 'usr-policy-06',
    name: 'Julian Thorne',
    email: 'julian.thorne@compliance.bank',
    role: 'POLICY_ADMINISTRATOR',
    department: 'Policy Architecture & Governance',
  },
  SYSTEM_ADMINISTRATOR: {
    id: 'usr-sysadmin-07',
    name: 'Alex Rivera',
    email: 'alex.rivera@tech.bank',
    role: 'SYSTEM_ADMINISTRATOR',
    department: 'Platform Infrastructure & Integrations',
  },
  AUDITOR: {
    id: 'usr-auditor-08',
    name: 'Rachel Adams',
    email: 'rachel.adams@internal-audit.bank',
    role: 'AUDITOR',
    department: 'Group Internal Audit',
  },
};

export function hasPermission(role: RoleId, permission: PermissionKey): boolean {
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
}

export function validateNoSelfApproval(actorId: string, requesterId: string, actionDesc = 'approval'): { valid: boolean; error?: string } {
  if (actorId === requesterId) {
    return {
      valid: false,
      error: `Segregation of Duties Violation: You cannot perform ${actionDesc} on a request you initiated (Requester ID: ${requesterId}). A secondary reviewer is required.`,
    };
  }
  return { valid: true };
}
